-- =============================================================================
-- Migration: 20260802000002_create_journey_tables.sql
-- Phase 7: Journey & Personal Growth Profile
-- =============================================================================

-- ─── Table: speaking_sessions ─────────────────────────────────────────────────
-- Lightweight record of each completed speaking session.
-- Does NOT store audio, transcripts, or raw AI responses.
-- Only the structured AI feedback fields are persisted.
CREATE TABLE public.speaking_sessions (
  id                  uuid        NOT NULL DEFAULT gen_random_uuid(),
  user_id             uuid        NOT NULL,
  topic               text        NOT NULL,
  mode                text        NOT NULL,
  duration_seconds    integer     NOT NULL DEFAULT 0,
  summary             text        NOT NULL DEFAULT '',
  strengths           jsonb       NOT NULL DEFAULT '[]'::jsonb,
  improvements        jsonb       NOT NULL DEFAULT '[]'::jsonb,
  clarity_feedback    text        NOT NULL DEFAULT '',
  vocabulary_feedback text        NOT NULL DEFAULT '',
  structure_feedback  text        NOT NULL DEFAULT '',
  filler_feedback     text        NOT NULL DEFAULT '',
  created_at          timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT speaking_sessions_pkey         PRIMARY KEY (id),
  CONSTRAINT speaking_sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES auth.users (id)
    ON DELETE CASCADE,
  CONSTRAINT speaking_sessions_mode_check   CHECK (mode IN ('off_the_cuff', 'research'))
);

COMMENT ON TABLE  public.speaking_sessions              IS 'Lightweight session record — structured feedback only. No transcript, no audio.';
COMMENT ON COLUMN public.speaking_sessions.user_id      IS 'References auth.users. Cascades on delete.';
COMMENT ON COLUMN public.speaking_sessions.mode         IS 'Speaking mode: off_the_cuff or research.';
COMMENT ON COLUMN public.speaking_sessions.strengths    IS 'JSON array of strength strings from AI feedback.';
COMMENT ON COLUMN public.speaking_sessions.improvements IS 'JSON array of improvement strings from AI feedback.';

CREATE INDEX speaking_sessions_user_id_idx         ON public.speaking_sessions (user_id);
CREATE INDEX speaking_sessions_user_created_at_idx ON public.speaking_sessions (user_id, created_at DESC);

ALTER TABLE public.speaking_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "speaking_sessions_select_own"
  ON public.speaking_sessions FOR SELECT
  TO authenticated USING (user_id = auth.uid());

CREATE POLICY "speaking_sessions_insert_own"
  ON public.speaking_sessions FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

CREATE POLICY "speaking_sessions_delete_own"
  ON public.speaking_sessions FOR DELETE
  TO authenticated USING (user_id = auth.uid());

-- ─── Table: communication_profiles ────────────────────────────────────────────
-- One row per user. Upserted after qualifying sessions.
-- Describes the user's communication style as it evolves over time.
CREATE TABLE public.communication_profiles (
  user_id         uuid        NOT NULL,
  profile_summary text        NOT NULL DEFAULT '',
  current_focus   text        NOT NULL DEFAULT '',
  total_sessions  integer     NOT NULL DEFAULT 0,
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT communication_profiles_pkey         PRIMARY KEY (user_id),
  CONSTRAINT communication_profiles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES auth.users (id)
    ON DELETE CASCADE
);

COMMENT ON TABLE  public.communication_profiles                 IS 'Evolving communication profile per user. One row per user, upserted after sessions.';
COMMENT ON COLUMN public.communication_profiles.profile_summary IS '2–4 sentence description of the user''s communication style.';
COMMENT ON COLUMN public.communication_profiles.current_focus   IS 'Single actionable focus for the next sessions.';
COMMENT ON COLUMN public.communication_profiles.total_sessions  IS 'Authoritative session count. Used to drive profile update cadence.';

CREATE TRIGGER communication_profiles_updated_at
  BEFORE UPDATE ON public.communication_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

ALTER TABLE public.communication_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "communication_profiles_select_own"
  ON public.communication_profiles FOR SELECT
  TO authenticated USING (user_id = auth.uid());

CREATE POLICY "communication_profiles_insert_own"
  ON public.communication_profiles FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

CREATE POLICY "communication_profiles_update_own"
  ON public.communication_profiles FOR UPDATE
  TO authenticated
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ─── Table: journey_letters ────────────────────────────────────────────────────
-- Milestone letters generated by Curio at sessions 25, 50, 100, 150, ...
CREATE TABLE public.journey_letters (
  id                uuid        NOT NULL DEFAULT gen_random_uuid(),
  user_id           uuid        NOT NULL,
  milestone_session integer     NOT NULL,
  content           text        NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT journey_letters_pkey                     PRIMARY KEY (id),
  CONSTRAINT journey_letters_user_milestone_key       UNIQUE (user_id, milestone_session),
  CONSTRAINT journey_letters_user_id_fkey             FOREIGN KEY (user_id)
    REFERENCES auth.users (id)
    ON DELETE CASCADE
);

COMMENT ON TABLE  public.journey_letters                    IS 'Milestone letters from Curio, generated at session 25, 50, 100, ...';
COMMENT ON COLUMN public.journey_letters.milestone_session  IS 'The session number that triggered this letter (25, 50, 100, ...).';
COMMENT ON COLUMN public.journey_letters.content            IS '150–250 word reflective letter from Curio.';

CREATE INDEX journey_letters_user_id_idx ON public.journey_letters (user_id);

ALTER TABLE public.journey_letters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "journey_letters_select_own"
  ON public.journey_letters FOR SELECT
  TO authenticated USING (user_id = auth.uid());
